version: "3"
services: 
  dev: 
    image: ekkremiskubernetes/splash-dev
    container_name: splash-test
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app/
      - node_modules:/usr/src/app/node_modules/
    command: "npm run dev:hot"
volumes: 
  node_modules: {}