version: "3"
services: 
  dev: 
    image: ekkremiskubernetes/splash-dev2
    container_name: splash-dev2
    ports:
      - "8080:8080"
    volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    command: "npm run dev:hot"
volumes: 
  node_modules: